version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install dbt-core dbt-postgres
      - echo "Logging in to Docker Hub..."
      - echo "lumiq121@" | docker login -u "spatika123" --password-stdin

  build:
    commands:
      - echo "Building project..."
      - dbt debug
      - echo "Building Docker image..."
      - docker build -t spatika123/dbt-project-image:latest .
      - docker push spatika123/dbt-project-image:latest
