version: 0.2

env:
  variables:
    DBT_TARGET: 'dev'

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install dbt-core dbt-postgres  
  build:
    commands:
      - echo "Building project..."
      - dbt debug  
